---
apiVersion: v1
kind: Secret
metadata:
  name: bgp-auth-secret
  namespace: kube-system
stringData:
  password: ${cilium_bgp_secret}
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: freenas-api-nvmeof-driver-config
  namespace: democratic-csi
type: Opaque
stringData:
  driver-config-file.yaml: |-
    driver: freenas-api-nvmeof
    instance_id:
    httpConnection:
      protocol: ${democratic_csi_truenas_api_protocol}
      host: ${democratic_csi_truenas_host}
      port: ${democratic_csi_truenas_api_port}
      apiKey: ${democratic_csi_truenas_api_key}
      allowInsecure: true

    zfs:
      datasetParentName: ${democratic_csi_truenas_zfs_dataset_parent_name}
      detachedSnapshotsDatasetParentName: ${democratic_csi_truenas_zfs_detached_snapshots_dataset_parent_name}
      zvolCompression: # "" (inherit), lz4, gzip-9, etc
      zvolDedup: # "" (inherit), on, off, verify
      zvolEnableReservation: false
      zvolBlocksize: 64K

    nvmeof:
      transports:
        - tcp://${democratic_csi_truenas_host}:${democratic_csi_truenas_nvmeof_port}

      nameTemplate: "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}-{{ parameters.[csi.storage.k8s.io/pvc/name] }}"
      namePrefix: "csi-"
      nameSuffix: "-talos"

      ports:
        - ${democratic_csi_truenas_nvmeof_port_index} # id/index curl -v 'http://username:password@IP/api/v2.0/nvmet/port'

      # http://<ip>/api/docs/current/api_methods_nvmet.subsys.create.html
      subsystemTemplate:
        pi_enable: true
        qid_max:
        ieee_oui:
        ana:

      # http://<ip>/api/docs/current/api_methods_nvmet.namespace.create.html
      # currently none of the fields can be tweaked so leave empty for now
      namespaceTemplate:
